# Default values for k0rdent-awx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backoffLimit: 4

awxServiceUrl: http://awx-service
awxAdminPasswordSecretName: awx-admin-password
awxAdminPasswordSecretKey: password

awxConfig:
  collectionGitUrl: https://github.com/dukov/ansible-collections-k0rdent.git
  collectionGitVersion: main
  # sshKeySecretName: ansible-ssh-key
  awxOrganizations: []
    # - name: "Default"
    #   description: "K0rdent Organization"
  awxProjects: []
    # - name: "k0rdent"
    #   scm_url: "https://github.com/dukov/k0redent-ansible-test"
    #   organization: "Default"
  awxInventories: []
    # - name: "k0rdent"
    #   organization: "Default"
    #   inventory_sources:
    #     - name: "k0rdent"
    #       source_project: "k0rdent"
    #       source_path: "k0rdent_nodes.yaml"
  awxInstanceGroups: []
    # - name: "default"
    #   pod_spec_override:
    #     spec:
    #       serviceAccountName: awx-inventory-reader
    #       automountServiceAccountToken: true
  awxJobTemplates: []
    # - name: "Production"
    #   job_type: "run"
    #   inventory: "k0rdent"
    #   project: "k0rdent"
    #   playbook: "production.yml"
    #   credentials:
    #     - "Machine Credential"
    #   schedules:
    #     - name: "Enforce State"
    #       rrule: "DTSTART:20240101T000000Z RRULE:FREQ=HOURLY;INTERVAL=1"
    #       enabled: true
  extraCollections: []

image:
  repository: quay.io/ansible/awx-ee
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "24.6.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: 
  fsGroup: 0
  fsGroupChangePolicy: OnRootMismatch
  runAsGroup: 0
  runAsUser: 0

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
