---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k0rdent-awx.fullname" . }}-rolebinding
  labels:
    {{- include "k0rdent-awx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k0rdent-awx.fullname" . }}-inventory-reader
subjects:
- kind: ServiceAccount
  name: {{ include "k0rdent-awx.fullname" . }}
  namespace: {{ .Release.Namespace }}