apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k0rdent-awx.fullname" . }}
  labels:
    {{- include "k0rdent-awx.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
